name: CI/CD Pipeline - DevSecOps

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=samarjeetyadav_aks-devsecops-demo
            -Dsonar.organization=samarjeetyadav
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Azure Login using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker login to ACR
        run: az acr login --name cybrainiumacr

      - name: Build and Push Docker Image
        run: |
          docker build -t cybrainiumacr.azurecr.io/aks-devsecops-demo:latest .
          docker push cybrainiumacr.azurecr.io/aks-devsecops-demo:latest

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
