    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: samarjeetyadav_aks-devsecops-demo
        SONAR_ORGANIZATION: samarjeetyadav
