    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=samarjeetyadav_aks-devsecops-demo
          -Dsonar.organization=samarjeetyadav
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.sources=.
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
